CREATE TABLE IF NOT EXISTS aiia_runtime_artifact (
  artifact_id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '运行时资产主键',
  artifact_type varchar(32) NOT NULL COMMENT '资产类型：tool/skill/job/workflow/prompt/policy',
  name varchar(128) NOT NULL COMMENT '资产稳定名称',
  version varchar(32) NOT NULL DEFAULT 'v1' COMMENT '版本号',
  status varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态：draft/active/deprecated/archived',
  display_name varchar(128) NOT NULL DEFAULT '' COMMENT '展示名称',
  description text DEFAULT NULL COMMENT '说明文本',
  owner varchar(64) NOT NULL DEFAULT '' COMMENT '归属域或维护方',
  domain varchar(64) NOT NULL DEFAULT '' COMMENT '业务域，如 market/runtime',
  capabilities_json json DEFAULT NULL COMMENT '能力标签数组',
  tags_json json DEFAULT NULL COMMENT '标签数组',
  keywords_json json DEFAULT NULL COMMENT '关键词数组',
  side_effect_level varchar(32) NOT NULL DEFAULT 'none' COMMENT '副作用等级：none/read_only/write_db/external_actuation',
  enabled tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  implementation_kind varchar(32) NOT NULL DEFAULT '' COMMENT '实现类型，如 python_callable/file_bundle',
  implementation_target varchar(255) NOT NULL DEFAULT '' COMMENT '实现目标，如 module:function',
  source_manifest_json json DEFAULT NULL COMMENT '源文件清单与路径',
  retrieval_text mediumtext DEFAULT NULL COMMENT '用于检索与路由的展开文本',
  current_revision_no int unsigned NOT NULL DEFAULT 0 COMMENT '当前修订号',
  sync_status varchar(32) NOT NULL DEFAULT 'synced' COMMENT '文件与数据库同步状态：synced/pending/failed/drift_detected',
  last_synced_at datetime DEFAULT NULL COMMENT '最近同步时间',
  created_by varchar(64) NOT NULL DEFAULT '' COMMENT '创建人或系统',
  updated_by varchar(64) NOT NULL DEFAULT '' COMMENT '最近更新人或系统',
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (artifact_id),
  UNIQUE KEY uniq_artifact_type_name_version (artifact_type, name, version),
  KEY idx_artifact_type_status (artifact_type, status, enabled),
  KEY idx_domain_enabled (domain, enabled),
  KEY idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='运行时资产注册表；统一承载 tool/skill/job/workflow 等定义索引';
