CREATE TABLE IF NOT EXISTS aiia_runtime_invocation (
  invocation_id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '调用主键',
  thread_id bigint unsigned DEFAULT NULL COMMENT '所属线程',
  turn_id bigint unsigned DEFAULT NULL COMMENT '所属轮次',
  task_id bigint unsigned DEFAULT NULL COMMENT '所属任务',
  event_id bigint unsigned DEFAULT NULL COMMENT '起始事件 ID',
  artifact_id bigint unsigned DEFAULT NULL COMMENT '调用的资产 ID',
  artifact_type varchar(32) NOT NULL DEFAULT '' COMMENT '调用资产类型',
  artifact_name varchar(128) NOT NULL DEFAULT '' COMMENT '调用资产名称',
  artifact_version varchar(32) NOT NULL DEFAULT '' COMMENT '调用资产版本',
  input_json longtext DEFAULT NULL COMMENT '调用输入',
  output_json longtext DEFAULT NULL COMMENT '调用输出',
  status varchar(32) NOT NULL DEFAULT 'completed' COMMENT '状态：running/completed/failed/timeout/cancelled',
  latency_ms int unsigned DEFAULT NULL COMMENT '延迟毫秒',
  token_usage_json json DEFAULT NULL COMMENT 'token 用量',
  error_text text DEFAULT NULL COMMENT '错误文本',
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (invocation_id),
  KEY idx_thread_created (thread_id, created_at),
  KEY idx_task_created (task_id, created_at),
  KEY idx_artifact_created (artifact_id, created_at),
  KEY idx_artifact_name_status (artifact_name, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='运行时调用表；记录 tool/skill/job/workflow 的执行输入输出与成本';
