-- Durable SMS challenge state for phone-based account registration.
-- Privacy boundary: neither the phone number nor verification code is stored;
-- both are keyed HMAC-SHA256 digests generated by the application.
CREATE TABLE IF NOT EXISTS aiia_phone_verification_challenge (
  challenge_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mobile_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  purpose VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_request_id VARCHAR(128) NULL,
  request_ip_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  resend_after DATETIME(6) NOT NULL,
  max_attempts TINYINT UNSIGNED NOT NULL,
  attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  send_succeeded_at DATETIME(6) NULL,
  send_failed_at DATETIME(6) NULL,
  verified_at DATETIME(6) NULL,
  consumed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (challenge_id),
  KEY idx_aiia_phone_challenge_mobile_created (mobile_hash, created_at),
  KEY idx_aiia_phone_challenge_ip_created (request_ip_hash, created_at),
  KEY idx_aiia_phone_challenge_created (created_at),
  KEY idx_aiia_phone_challenge_consumption (
    mobile_hash,
    verified_at,
    consumed_at
  ),
  KEY idx_aiia_phone_challenge_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
  COMMENT='Phone possession verification challenges; no phone/code plaintext';
