-- 公告结构化首批样本；2026-10-02，用户已授权在 kingdomai 新建独立表。
-- 仅新建四张 notice 表，不改 PG news_notice、研报表或旧公告表。
-- 无 CREATE IF NOT EXISTS：遇到同名表先核对结构，不静默复用。
USE kingdomai;

CREATE TABLE notice_documents (
  document_version_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  document_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  batch_id VARCHAR(96) NOT NULL COMMENT '样本/抽取批次，便于筛选和复核',
  source_system VARCHAR(128) NOT NULL,
  source_record_id VARCHAR(128) NULL,
  source_url TEXT NOT NULL,
  resolved_url TEXT NULL,
  title VARCHAR(1024) NOT NULL,
  issuer_name VARCHAR(255) NULL COMMENT '正文披露主体原称；不据证券代码猜法人',
  security_code_raw VARCHAR(128) NULL,
  security_code VARCHAR(32) NULL COMMENT '仅经主数据确认时填写',
  market VARCHAR(32) NULL,
  source_type VARCHAR(64) NULL,
  source_type_new VARCHAR(64) NULL,
  business_category VARCHAR(96) NULL COMMENT '主检索分类，非排他的业务约束',
  document_form VARCHAR(96) NULL,
  language VARCHAR(32) NULL,
  source_name VARCHAR(128) NULL,
  published_at_raw VARCHAR(128) NULL,
  published_at DATETIME(6) NULL COMMENT '保留源墙上时间；时区及精度说明见 published_time_note',
  published_time_note VARCHAR(255) NULL,
  source_updated_at VARCHAR(128) NULL,
  observed_at DATETIME(6) NOT NULL COMMENT 'UTC',
  content_text LONGTEXT NULL COMMENT '本次证据正文快照；补解析也仅存目标库，源 PG 不更新',
  content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  original_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  original_ref TEXT NULL COMMENT '本次本地归档引用；尚未作为线上文件服务',
  parser_version VARCHAR(128) NULL,
  extraction_version VARCHAR(128) NOT NULL,
  extraction_model VARCHAR(128) NOT NULL,
  structured_at DATETIME(6) NOT NULL COMMENT 'UTC',
  summary TEXT NULL,
  extraction_notes TEXT NULL,
  `ignore` BOOLEAN NOT NULL DEFAULT FALSE,
  ignore_reason TEXT NULL,
  selection_version VARCHAR(128) NOT NULL,
  KEY idx_notice_doc_key (document_key),
  KEY idx_notice_batch_category (batch_id, business_category),
  KEY idx_notice_security_date (security_code_raw, published_at),
  KEY idx_notice_publish (published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告文档与抽取版本；初批为人工式逐篇研读样本，不代表全量覆盖';

CREATE TABLE notice_events (
  event_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  document_version_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_no SMALLINT UNSIGNED NOT NULL,
  event_type VARCHAR(128) NULL,
  event_title VARCHAR(512) NOT NULL,
  event_summary TEXT NOT NULL,
  event_date DATE NULL,
  key_dates JSON NULL COMMENT '有查询用途的命名日期及原文依据；不作为任意属性袋',
  related_documents JSON NULL COMMENT '明确的前次披露引用；未定位 URL 时只保留原文描述',
  source_quote TEXT NOT NULL,
  source_locator JSON NOT NULL COMMENT '正文 hash、Unicode 字符半开区间；PDF物理页仅确有页映射时填写',
  UNIQUE KEY uq_notice_event_no (document_version_id, event_no),
  UNIQUE KEY uq_notice_event_owner (document_version_id, event_id),
  KEY idx_notice_event_type_date (event_type, event_date),
  CONSTRAINT fk_notice_event_doc FOREIGN KEY (document_version_id) REFERENCES notice_documents(document_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告中的具体事项与此次变化';

CREATE TABLE notice_metric_facts (
  fact_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  document_version_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  fact_no SMALLINT UNSIGNED NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  scope TEXT NULL,
  metric_code VARCHAR(64) NULL COMMENT '仅定义完全匹配才复用 metric_def；空值不妨碍原名检索',
  metric_name VARCHAR(255) NOT NULL,
  value_raw VARCHAR(1024) NOT NULL,
  value_num DECIMAL(30,8) NULL,
  value_lower DECIMAL(30,8) NULL,
  value_upper DECIMAL(30,8) NULL,
  unit_raw VARCHAR(64) NULL,
  unit_code VARCHAR(32) NULL COMMENT '数值量级跟随单位，不默认归一为元',
  currency VARCHAR(16) NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  period_label VARCHAR(128) NULL,
  as_of_date DATE NULL,
  value_type VARCHAR(32) NULL COMMENT 'actual/forecast 仅语义明确时填写；计划、上限等由 basis 说明',
  basis TEXT NULL,
  source_quote TEXT NOT NULL,
  source_locator JSON NOT NULL,
  extraction_notes TEXT NULL,
  UNIQUE KEY uq_notice_fact_no (document_version_id, fact_no),
  KEY idx_notice_fact_name_period (metric_name, period_end),
  KEY idx_notice_fact_subject (subject_name, as_of_date),
  CONSTRAINT fk_notice_fact_doc FOREIGN KEY (document_version_id) REFERENCES notice_documents(document_version_id),
  CONSTRAINT fk_notice_fact_event_owner FOREIGN KEY (document_version_id, event_id) REFERENCES notice_events(document_version_id, event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='可定位的公告数值、期间、单位、范围；原披露与计划口径不可混算';

CREATE TABLE notice_participants (
  participant_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  event_id CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  participant_no SMALLINT UNSIGNED NOT NULL,
  name_raw VARCHAR(255) NOT NULL,
  name_normalized VARCHAR(255) NULL,
  role VARCHAR(128) NOT NULL COMMENT '事项内角色，不是主体永久属性',
  role_description TEXT NULL,
  source_quote TEXT NOT NULL,
  source_locator JSON NOT NULL,
  UNIQUE KEY uq_notice_participant_no (event_id, participant_no),
  KEY idx_notice_participant_role (name_raw, role),
  CONSTRAINT fk_notice_participant_event FOREIGN KEY (event_id) REFERENCES notice_events(event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='事项参与方及证据，借款人与保证人等角色分开';
